name: Quote Getter

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Quote
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository content
        uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install django

      - name: execute py script # run main.py
        run: python Quoter.py

      - name: Commit quote
        run: |
          git config --global user.name 'dikiv'
          git config --global user.email 'dikiv@users.noreply.github.com'
          git commit -am "Automated report"
          git push