name: Quote Getter

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Quote
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository content
        uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install django

      - name: execute py script 
        run: python Quoter.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated files" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: main